### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by marioecg**
Added requirements.txt to the repository

### CODE REVIEW

**Comment by aewens** [comment]
Halfway there. The project includes some packages, so we need those included in the requirements.txt file.

**Comment by marioecg** [comment]
@aewens okay, which packages specifically so I can add them in the file?

**Comment by aewens** [comment]
The package in [app.py](https://github.com/tildecross/tildex-notify/blob/master/app.py)

**Comment by aewens** [comment]
Thank you for submitting a pull request, but issue #4 was resolved in [PR #9 ](https://github.com/tildecross/tildex-notify/pull/9)

**Pull request closed without merging**
